### ISSUE TITLE
11/08/2024 - Failure of Whisper-diarization Google Colab script

### ISSUE THREAD

**Issue by BlohoJo** [Transcripts4All/tools4all#6]
https://colab.research.google.com/github/Transcripts4All/tools4all/blob/main/whisper-diarization.ipynb

It's not working again... not sure what happened this time. I'm guessing more changes upstream that break existing scripts. I know it really makes it frustrating to keep up with when repositories make script-breaking changes often, which seems to be the case with some of the repositories Whisper-diarization uses.

(Using Pastebin to get around Girhub's maximum body length.)

Step 1: https://pastebin.com/H8D1XXuw

Runtime -> Restart Session

Step 2: https://pastebin.com/RnHYQMKk

**Comment by BlohoJo** [comment]
Noticed this in Step 1:

Line 335:
`sentence-transformers 3.2.1 requires transformers<5.0.0,>=4.41.0, but you have transformers 4.39.3 which is incompatible.`

Line 606:
`gcsfs 2024.10.0 requires fsspec==2024.10.0, but you have fsspec 2024.9.0 which is incompatible.`

Line 607:
`sentence-transformers 3.2.1 requires transformers<5.0.0,>=4.41.0, but you have transformers 4.39.3 which is incompatible.`

Shouldn't the scripts be downloading the latest versions automatically?

**Comment by ScriptTiger** [comment]
> Shouldn't the scripts be downloading the latest versions automatically?

The latest scripts are downloaded, but I had the notebook intentionally reverting to an older version. Ideally, yes, using the latest things is great. However, that repo's primary focus is research and development, while this repo's primary focus is production and getting work done. So, rather than just use the latest things, we focus on making sure things work. And oftentimes while they are refactoring/upgrading/updating, the upstream repo breaks. So, again, that's why I'll pin this repo to an older version so we can still continue to work while that one is down.

However, I've just tested the latest version and it seems a bit more stable now, until it isn't. So, I've just updated the notebook to reflect the latest changes made to the upstream repo. However, as I've stated, as soon as it breaks again, I'll revert it again and freeze it on an older version.
